var VOCAB_LIST = [{"english":"English","romaji":"Romaji","kana":"Kana","tags":"Tags,lesson Lesson"},
{"english":"sock","romaji":"kutsushita","kana":"くつした","tags":"clothes,lesson 1"},
{"english":"food","romaji":"tabemono","kana":"たべもの","tags":"food,lesson 1"},
{"english":"red","romaji":"akai","kana":"あかい","tags":"colors,lesson 1"},
{"english":"fruit","romaji":"kudamono","kana":"くだもの","tags":"food,lesson 1"},
{"english":"circle","romaji":"maru","kana":"まる","tags":"shapes,lesson 1"},
{"english":"delicious","romaji":"oishii","kana":"おいしい","tags":"food,lesson 1"},
{"english":"peel","romaji":"kawa","kana":"かわ","tags":"food,lesson 1"},
{"english":"apple","romaji":"ringo","kana":"りんご","tags":"food,lesson 1"},
{"english":"tomato","romaji":"tomato","kana":"トマト","tags":"food,lesson 1"},
{"english":"banana","romaji":"banana","kana":"バナナ","tags":"food,lesson 1"},
{"english":"orange (fruit)","romaji":"orengi","kana":"オレンジ","tags":"food,lesson 1"},
{"english":"cake","romaji":"kēki","kana":"ケーキ","tags":"food,lesson 1"},
{"english":"chocolate","romaji":"chokorēto","kana":"チョコレート","tags":"food,lesson 1"},
{"english":"book","romaji":"hon","kana":"ほん","tags":"school,lesson 1"},
{"english":"pencil","romaji":"enpitsu","kana":"えんぴつ","tags":"school,lesson 1"},
{"english":"stamp (postage)","romaji":"kitte","kana":"きって","tags":"lesson 1"},
{"english":"magazine","romaji":"zasshi","kana":"ざっし","tags":"home,lesson 1"},
{"english":"soccer","romaji":"sakkā","kana":"サッカー","tags":"sports,lesson 1"},
{"english":"judo","romaji":"jūdō","kana":"じゅど","tags":"sports,lesson 1"},
{"english":"good morning","romaji":"ohayō","kana":"おはよう","tags":"salutations, conversation,lesson 1"},
{"english":"good morning (formal)","romaji":"ohayōgozaimasu","kana":"おはようございます","tags":"salutations, conversation,lesson 1"},
{"english":"hello","romaji":"kon'nichiwa","kana":"こんにちは","tags":"salutations, conversation,lesson 1"},
{"english":"good evening","romaji":"konbanwa","kana":"こんばんは","tags":"salutations, conversation,lesson 1"},
{"english":"goodbye","romaji":"sayōnara","kana":"さようなら","tags":"salutations, conversation,lesson 1"},
{"english":"goodbye (informal)","romaji":"ja ne","kana":"じゃね","tags":"salutations, conversation,lesson 1"},
{"english":"good night","romaji":"oyasumi","kana":"おやすみ","tags":"salutations, conversation,lesson 1"},
{"english":"good night (formal)","romaji":"oyasuminasai","kana":"おやすみなさい","tags":"salutations, conversation,lesson 1"},
{"english":"month (suffix)","romaji":"-gatsu","kana":"〜がつ","tags":"time,lesson 1"},
{"english":"eight","romaji":"hachi","kana":"はち","tags":"numbers,lesson 1"},
{"english":"month","romaji":"tsuki","kana":"つき","tags":"time,lesson 1"},
{"english":"day (of the month)","romaji":"-nichi","kana":"〜にち","tags":"time,lesson 1"},
{"english":"moon","romaji":"tsuki","kana":"つき","tags":"weather,lesson 1"},
{"english":"saturday","romaji":"doyōbi","kana":"どようび","tags":"time, days of the week,lesson 1"},
{"english":"please lend me it","romaji":"kashite kudasai","kana":"かしてください","tags":"conversation,lesson 1"},
{"english":"please","romaji":"kudasai","kana":"てください","tags":"conversation,lesson 1"},
{"english":"go ahead","romaji":"dōzo","kana":"どうぞ","tags":"conversation,lesson 1"},
{"english":"no","romaji":"inai","kana":"いない","tags":"conversation,lesson 1"},
{"english":"wait a minute","romaji":"chotto matte","kana":"ちょっと　まって","tags":"conversation,lesson 1"},
{"english":"yes","romaji":"hai","kana":"はい","tags":"conversation,lesson 1"},
{"english":"no (casual)","romaji":"dame","kana":"だめ","tags":"conversation,lesson 1"},
{"english":"my name is ___.","romaji":"watashi wa ___ desu.","kana":"わたしは　＿です。","tags":"conversation,lesson 1"},
{"english":"I (androgynous)","romaji":"watashi","kana":"わたし","tags":"lesson 1"},
{"english":"I (androgynous)","romaji":"washi","kana":"わし","tags":"lesson 1"},
{"english":"I (male)","romaji":"boku","kana":"ぼく","tags":"lesson 1"},
{"english":"I (male, casual)","romaji":"ore","kana":"オレ","tags":"lesson 1"},
{"english":"I (female)","romaji":"uchi","kana":"うち","tags":"lesson 1"},
{"english":"white","romaji":"shiro","kana":"しろ","tags":"colors,lesson 1"},
{"english":"scary","romaji":"kowai","kana":"こわい","tags":"lesson 1"},
{"english":"ghost","romaji":"obake","kana":"おばけ","tags":"lesson 1"},
{"english":"sad","romaji":"kanashī","kana":"かなし","tags":"emotion,lesson 1"},
{"english":"wet","romaji":"nureta","kana":"ぬれた","tags":"lesson 1"},
{"english":"salty","romaji":"shoppai","kana":"しょっぱい","tags":"lesson 1"},
{"english":"tears","romaji":"namida","kana":"なみだ","tags":"lesson 1"},
{"english":"paper","romaji":"kami","kana":"かみ","tags":"school,lesson 1"},
{"english":"envelope","romaji":"fūtō","kana":"ふと","tags":"lesson 1"},
{"english":"letter","romaji":"tegami","kana":"てがみ","tags":"lesson 1"},
{"english":"night","romaji":"yoru","kana":"よる","tags":"weather,lesson 1"},
{"english":"sky","romaji":"sora","kana":"そら","tags":"weather,lesson 1"},
{"english":"stars","romaji":"hoshi","kana":"ほし","tags":"weather,lesson 1"},
{"english":"dark","romaji":"kurai","kana":"くらい","tags":"lesson 1"},
{"english":"yellow","romaji":"kiiro","kana":"きいろ","tags":"colors,lesson 1"},
{"english":"rain","romaji":"ame","kana":"あめ","tags":"weather,lesson 1"},
{"english":"cloud","romaji":"kumo","kana":"くも","tags":"weather,lesson 1"},
{"english":"lightning","romaji":"kaminari","kana":"まみなり","tags":"weather,lesson 1"},
{"english":"button","romaji":"botan","kana":"ボタン","tags":"lesson 1"},
{"english":"TV","romaji":"terebi","kana":"テレビ","tags":"home,lesson 1"},
{"english":"box","romaji":"hako","kana":"はこ","tags":"lesson 1"},
{"english":"school","romaji":"gakkō","kana":"がっこ","tags":"school,lesson 1"},
{"english":"back","romaji":"bakku","kana":"バック","tags":"body parts,lesson 1"},
{"english":"carry","romaji":"hakobu","kana":"はこぶ","tags":"lesson 1"},
{"english":"cold (illness)","romaji":"kaze","kana":"かぜ","tags":"lesson 1"},
{"english":"desk","romaji":"tsukue","kana":"つくえ","tags":"school,lesson 1"},
{"english":"tissue paper","romaji":"tisshupēpā","kana":"ティッシュペーパー","tags":"home,lesson 1"},
{"english":"are you ok?","romaji":"daijōbudesuka","kana":"大丈夫ですか","tags":"conversation,lesson 1"},
{"english":"friend","romaji":"tomo","kana":"とも","tags":"lesson 1"},
{"english":"Japanese syllabary (native words)","romaji":"hiragana","kana":"ひらがな","tags":"lesson 1"},
{"english":"Japanese syllabary (loan words)","romaji":"katakana","kana":"カタカナ","tags":"lesson 1"},
{"english":"sunny","romaji":"hare","kana":"はれ","tags":"weather,lesson 2"},
{"english":"boy (suffix)","romaji":"-kun","kana":"くん","tags":"lesson 2"},
{"english":"boy/girl (suffix)","romaji":"-chan","kana":"ちゃん","tags":"lesson 2"},
{"english":"Mr., Mrs., Ms. (suffix)","romaji":"-san","kana":"さん","tags":"lesson 2"},
{"english":"Japan","romaji":"nihon","kana":"にほん","tags":"countries,lesson 2"},
{"english":"Spain","romaji":"supein","kana":"スペイン","tags":"countries,lesson 2"},
{"english":"Russia","romaji":"roshia","kana":"ロシア","tags":"countries,lesson 2"},
{"english":"Switzerland","romaji":"suisu","kana":"スイス","tags":"countries,lesson 2"},
{"english":"excuse me","romaji":"shitsureidesuga","kana":"しつれいですが","tags":"conversation,lesson 2"},
{"english":"right (direction)","romaji":"migi","kana":"みぎ","tags":"lesson 2"},
{"english":"duck","romaji":"ahiru","kana":"アヒル","tags":"animals,lesson 2"},
{"english":"dog","romaji":"inu","kana":"いぬ","tags":"animals,lesson 2"},
{"english":"rabbit","romaji":"usagi","kana":"うさぎ","tags":"animals,lesson 2"},
{"english":"parrot","romaji":"ōmu","kana":"おむ","tags":"animals,lesson 2"},
{"english":"foot, leg","romaji":"ashi","kana":"あし","tags":"body parts,lesson 2"},
{"english":"fan","romaji":"uchiwa","kana":"うちわ","tags":"lesson 2"},
{"english":"number","romaji":"sūji","kana":"すじ","tags":"numbers,lesson 2"},
{"english":"time","romaji":"jikan","kana":"じかん","tags":"time,lesson 2"},
{"english":"alarm clock","romaji":"mezamashidokei","kana":"めざましどけい","tags":"time,lesson 2"},
{"english":"wall clock","romaji":"hashiradokei","kana":"はしらどけい","tags":"time,lesson 2"},
{"english":"clock, watch","romaji":"tokei","kana":"とけい","tags":"time,lesson 2"},
{"english":"fire","romaji":"hi","kana":"ひ","tags":"lesson 2"},
{"english":"smoke","romaji":"kemuri","kana":"けむり","tags":"lesson 2"},
{"english":"cigarette","romaji":"tabako","kana":"たばこ","tags":"lesson 2"},
{"english":"switch","romaji":"suitchi","kana":"スイッチ","tags":"lesson 2"},
{"english":"lighter","romaji":"raitā","kana":"ライター","tags":"lesson 2"},
{"english":"soft","romaji":"yawarakai","kana":"やわらかい","tags":"lesson 2"},
{"english":"ocean","romaji":"umi","kana":"うみ","tags":"lesson 2"},
{"english":"glue","romaji":"nori","kana":"のり","tags":"school,lesson 2"},
{"english":"small","romaji":"chīsai","kana":"ちいさい","tags":"lesson 2"},
{"english":"small","romaji":"sukunai","kana":"すくない","tags":"lesson 2"},
{"english":"raw","romaji":"nama","kana":"なま","tags":"lesson 2"},
{"english":"card","romaji":"kādo","kana":"カード","tags":"lesson 2"},
{"english":"electricity","romaji":"denki","kana":"でんき","tags":"lesson 2"},
{"english":"wood","romaji":"ki","kana":"き","tags":"lesson 2"},
{"english":"chop sticks","romaji":"hashi","kana":"はし","tags":"lesson 2"},
{"english":"cute","romaji":"kawaii","kana":"かわいい","tags":"lesson 2"},
{"english":"cat","romaji":"neko","kana":"ねこ","tags":"animals,lesson 2"},
{"english":"brown","romaji":"chairo","kana":"ちゃいろ","tags":"colors,lesson 2"},
{"english":"“ah” / “a”","romaji":"","kana":"あ","tags":"hiragana, kana,lesson 2"},
{"english":"“ee” / “i”","romaji":"","kana":"い","tags":"hiragana, kana,lesson 2"},
{"english":"“oo” / “o”","romaji":"","kana":"う","tags":"hiragana, kana,lesson 2"},
{"english":"“ay” / “e”","romaji":"","kana":"え","tags":"hiragana, kana,lesson 2"},
{"english":"“oh” / “o”","romaji":"","kana":"お","tags":"hiragana, kana,lesson 2"},
{"english":"“ka”","romaji":"","kana":"か","tags":"hiragana, kana,lesson 3"},
{"english":"“ki”","romaji":"","kana":"き","tags":"hiragana, kana,lesson 3"},
{"english":"“ku”","romaji":"","kana":"く","tags":"hiragana, kana,lesson 3"},
{"english":"“ke”","romaji":"","kana":"け","tags":"hiragana, kana,lesson 3"},
{"english":"“ko”","romaji":"","kana":"こ","tags":"hiragana, kana,lesson 3"},
{"english":"one","romaji":"ichi","kana":"いち","tags":"numbers,lesson 3"},
{"english":"two","romaji":"ni","kana":"に","tags":"numbers,lesson 3"},
{"english":"three","romaji":"san","kana":"さん","tags":"numbers,lesson 3"},
{"english":"four","romaji":"shi","kana":"し","tags":"numbers,lesson 3"},
{"english":"five","romaji":"go","kana":"ご","tags":"numbers,lesson 3"},
{"english":"six","romaji":"roku","kana":"ろく","tags":"numbers,lesson 3"},
{"english":"seven","romaji":"shichi","kana":"しち","tags":"numbers,lesson 3"},
{"english":"nine","romaji":"kyū","kana":"きゅ","tags":"numbers,lesson 3"},
{"english":"ten","romaji":"jū","kana":"じゅ","tags":"numbers,lesson 3"},
{"english":"left (direction)","romaji":"hidari","kana":"ひだり","tags":"lesson 3"},
{"english":"umbrella","romaji":"kasa","kana":"かさ","tags":"weather,lesson 3"},
{"english":"hard candy","romaji":"amè","kana":"あめ","tags":"food,lesson 3"},
{"english":"giraffe","romaji":"kirin","kana":"きりん","tags":"animals,lesson 3"},
{"english":"whale","romaji":"kujira","kana":"くじら","tags":"animals,lesson 3"},
{"english":"bat","romaji":"komori","kana":"こうもり","tags":"animals,lesson 3"},
{"english":"child","romaji":"kodomo","kana":"こども","tags":"family,lesson 3"},
{"english":"mother","romaji":"okāsan","kana":"おかあさん","tags":"family,lesson 3"},
{"english":"sweet","romaji":"amai","kana":"あまい","tags":"food,lesson 3"},
{"english":"blue","romaji":"ao","kana":"あお","tags":"colors,lesson 3"},
{"english":"stick","romaji":"bō","kana":"ぼ","tags":"lesson 3"},
{"english":"daddy","romaji":"papa","kana":"パパ","tags":"family,lesson 3"},
{"english":"mommy","romaji":"mama","kana":"ママ","tags":"family,lesson 3"},
{"english":"person","romaji":"kata","kana":"かた","tags":"lesson 3"},
{"english":"beast","romaji":"yajū","kana":"やじゅ","tags":"animals,lesson 3"},
{"english":"scaly","romaji":"uroko","kana":"うろこ","tags":"lesson 3"},
{"english":"horn","romaji":"tsuno","kana":"つの","tags":"lesson 3"},
{"english":"dragon","romaji":"doragon","kana":"ドラゴン","tags":"animals,lesson 3"},
{"english":"bottle","romaji":"botoru","kana":"ボトル","tags":"home,lesson 3"},
{"english":"skin","romaji":"hada","kana":"はだ","tags":"body parts,lesson 3"},
{"english":"valuable","romaji":"kichō","kana":"きちょ","tags":"lesson 3"},
{"english":"metal","romaji":"kinzoku","kana":"きんぞく","tags":"lesson 3"},
{"english":"gold","romaji":"kin","kana":"きん","tags":"lesson 3"},
{"english":"gooey","romaji":"becha becha","kana":"べちゃべちゃ","tags":"lesson 3"},
{"english":"“sa”","romaji":"","kana":"さ","tags":"hiragana, kana,lesson 4"},
{"english":"“shi”","romaji":"","kana":"し","tags":"hiragana, kana,lesson 4"},
{"english":"“su”","romaji":"","kana":"す","tags":"hiragana, kana,lesson 4"},
{"english":"“se”","romaji":"","kana":"せ","tags":"hiragana, kana,lesson 4"},
{"english":"“so”","romaji":"","kana":"そ","tags":"hiragana, kana,lesson 4"},
{"english":"what is this?","romaji":"korewanandesuka","kana":"これはなんですか","tags":"conversation,lesson 4"},
{"english":"yes, it is","romaji":"hai sõdesu","kana":"はいそうです","tags":"conversation,lesson 4"},
{"english":"cloudy","romaji":"kumori","kana":"くもり","tags":"weather,lesson 4"},
{"english":"stone","romaji":"ishi","kana":"いし","tags":"nature,lesson 4"},
{"english":"fish","romaji":"sakana","kana":"さかな","tags":"animals,lesson 4"},
{"english":"stripes","romaji":"shima","kana":"しま","tags":"lesson 4"},
{"english":"horse","romaji":"uma","kana":"うま","tags":"animals,lesson 4"},
{"english":"zebra","romaji":"shimauma","kana":"シマウマ","tags":"animals,lesson 4"},
{"english":"watermelon","romaji":"suika","kana":"すいか","tags":"food,lesson 4"},
{"english":"cicada","romaji":"semi","kana":"せみ","tags":"animals,lesson 4"},
{"english":"soft serve","romaji":"sofutokurīmu","kana":"ソフトクリーム","tags":"food,lesson 4"},
{"english":"wallet","romaji":"saifu","kana":"さいふ","tags":"money,lesson 4"},
{"english":"washing machine","romaji":"Sentakuki","kana":"せんたくき","tags":"home,lesson 4"},
{"english":"machine","romaji":"kikai","kana":"きかい","tags":"lesson 4"},
{"english":"machine (suffix)","romaji":"-ki","kana":"き","tags":"lesson 4"},
{"english":"deer","romaji":"shika","kana":"しき","tags":"animals,lesson 4"},
{"english":"vacuum cleaner","romaji":"sōjiki","kana":"そうじき","tags":"home,lesson 4"},
{"english":"bag (satchel)","romaji":"kaban","kana":"かばん","tags":"lesson 4"},
{"english":"squirrel","romaji":"risu","kana":"りす","tags":"animals,lesson 4"},
{"english":"rice","romaji":"gohan","kana":"ごはん","tags":"food,lesson 4"},
{"english":"acorn","romaji":"donguri","kana":"ドングリ","tags":"nature,lesson 4"},
{"english":"sky blue","romaji":"mizuiro","kana":"みずいろ","tags":"colors,lesson 4"},
{"english":"lunch","romaji":"bentō","kana":"べんとう","tags":"food,lesson 4"},
{"english":"finger","romaji":"yubi","kana":"ゆび","tags":"body parts,lesson 4"},
{"english":"chick (animal)","romaji":"hiyoko","kana":"ひよこ","tags":"animals,lesson 4"},
{"english":"dove","romaji":"hato","kana":"はと","tags":"animals,lesson 4"},
{"english":"fat","romaji":"futotteiru","kana":"ふとっている","tags":"lesson 4"},
{"english":"mushroom","romaji":"kinoko","kana":"キノコ","tags":"nature,lesson 4"},
{"english":"sea","romaji":"umi","kana":"うみ","tags":"nature,lesson 4"},
{"english":"hard","romaji":"katai","kana":"かたい","tags":"lesson 4"},
{"english":"beach","romaji":"kaigan","kana":"かいがん","tags":"nature,lesson 4"},
{"english":"shell","romaji":"kara","kana":"から","tags":"nature,lesson 4"},
{"english":"“ta”","romaji":"","kana":"た","tags":"hiragana, kana,lesson 5"},
{"english":"“chi”","romaji":"","kana":"ち","tags":"hiragana, kana,lesson 5"},
{"english":"“tsu”","romaji":"","kana":"つ","tags":"hiragana, kana,lesson 5"},
{"english":"“te”","romaji":"","kana":"て","tags":"hiragana, kana,lesson 5"},
{"english":"“to”","romaji":"","kana":"と","tags":"hiragana, kana,lesson 5"},
{"english":"egg","romaji":"tamago","kana":"たまご","tags":"food,lesson 5"},
{"english":"fingernail","romaji":"tsune","kana":"つめ","tags":"body parts,lesson 5"},
{"english":"octopus","romaji":"tako","kana":"タコ","tags":"animals,lesson 5"},
{"english":"kite","romaji":"tako","kana":"たこ","tags":"lesson 5"},
{"english":"blood","romaji":"chi","kana":"ち","tags":"body parts,lesson 5"},
{"english":"ladybug","romaji":"tentōmushi","kana":"てんとうむし","tags":"animals,lesson 5"},
{"english":"hand","romaji":"te","kana":"て","tags":"body parts,lesson 5"},
{"english":"pen","romaji":"pen","kana":"ペン","tags":"school,lesson 5"},
{"english":"long","romaji":"nagai","kana":"ながい","tags":"lesson 5"},
{"english":"thin","romaji":"hosoi","kana":"ほそい","tags":"lesson 5"},
{"english":"green","romaji":"midori","kana":"みどり","tags":"colors,lesson 5"},
{"english":"drink (noun)","romaji":"nomu","kana":"のむ","tags":"lesson 5"},
{"english":"drinking straw","romaji":"sutorō","kana":"ストロー","tags":"lesson 5"},
{"english":"candy","romaji":"okashi","kana":"おかし","tags":"food,lesson 5"},
{"english":"sliver","romaji":"gin","kana":"ぎん","tags":"lesson 5"},
{"english":"“na”","romaji":"","kana":"な","tags":"hiragana, kana,lesson 6"},
{"english":"“ni”","romaji":"","kana":"に","tags":"hiragana, kana,lesson 6"},
{"english":"“nu”","romaji":"","kana":"ぬ","tags":"hiragana, kana,lesson 6"},
{"english":"“ne”","romaji":"","kana":"ね","tags":"hiragana, kana,lesson 6"},
{"english":"“no”","romaji":"","kana":"の","tags":"hiragana, kana,lesson 6"},
{"english":"“ha”","romaji":"","kana":"は","tags":"hiragana, kana,lesson 7"},
{"english":"“hi”","romaji":"","kana":"ひ","tags":"hiragana, kana,lesson 7"},
{"english":"“hu”","romaji":"","kana":"ふ","tags":"hiragana, kana,lesson 7"},
{"english":"“he”","romaji":"","kana":"へ","tags":"hiragana, kana,lesson 7"},
{"english":"“ho”","romaji":"","kana":"ほ","tags":"hiragana, kana,lesson 7"},
{"english":"“ma”","romaji":"","kana":"ま","tags":"hiragana, kana,lesson 8"},
{"english":"“mi”","romaji":"","kana":"み","tags":"hiragana, kana,lesson 8"},
{"english":"“mu”","romaji":"","kana":"む","tags":"hiragana, kana,lesson 8"},
{"english":"“me”","romaji":"","kana":"め","tags":"hiragana, kana,lesson 8"},
{"english":"“mo”","romaji":"","kana":"も","tags":"hiragana, kana,lesson 8"},
{"english":"window","romaji":"mado","kana":"まど","tags":"home,lesson 8"},
{"english":"cavity (tooth)","romaji":"mushiba","kana":"むしば","tags":"lesson 8"},
{"english":"duh!","romaji":"ataremaejen","kana":"あたれまえじゃん","tags":"conversation,lesson 8"},
{"english":"peas","romaji":"mame","kana":"まめ","tags":"food,lesson 8"},
{"english":"mandarin orange (fruit)","romaji":"mikan","kana":"みかん","tags":"food,lesson 8"},
{"english":"glasses","romaji":"megane","kana":"めがな","tags":"lesson 8"},
{"english":"ear","romaji":"mimi","kana":"みみ","tags":"body parts,lesson 8"},
{"english":"peach","romaji":"momo","kana":"もも","tags":"food,lesson 8"},
{"english":"fifty-fifty","romaji":"han-han","kana":"はんーはん","tags":"conversation,lesson 8"},
{"english":"page","romaji":"pēji","kana":"ページ","tags":"lesson 8"},
{"english":"neck","romaji":"kubi","kana":"くび","tags":"body parts,lesson 8"},
{"english":"shiny","romaji":"hikaru","kana":"ひかる","tags":"lesson 8"},
{"english":"tool","romaji":"kōgu","kana":"こおぐ","tags":"lesson 8"},
{"english":"“ya”","romaji":"","kana":"や","tags":"hiragana, kana,lesson 9"},
{"english":"“yu”","romaji":"","kana":"ゆ","tags":"hiragana, kana,lesson 9"},
{"english":"“yo”","romaji":"","kana":"よ","tags":"hiragana, kana,lesson 9"},
{"english":"kettle","romaji":"yakan","kana":"やかん","tags":"home,lesson 9"},
{"english":"snowman","romaji":"yukidaruma","kana":"ゆきだるま","tags":"lesson 9"},
{"english":"snow","romaji":"yuki","kana":"ゆき","tags":"weather,lesson 9"},
{"english":"after you","romaji":"osakini dōzo","kana":"おさきに　どうぞ","tags":"lesson 9"},
{"english":"mountain","romaji":"yama","kana":"やま","tags":"nature,lesson 9"},
{"english":"sailboat, yacht","romaji":"yotto","kana":"ヨット","tags":"lesson 9"},
{"english":"hiccups","romaji":"shakkuri","kana":"しゃっくり","tags":"lesson 9"},
{"english":"sun","romaji":"nichi","kana":"にち","tags":"lesson 9"},
{"english":"“ra”","romaji":"","kana":"ら","tags":"hiragana, kana,lesson 10"},
{"english":"“ri”","romaji":"","kana":"り","tags":"hiragana, kana,lesson 10"},
{"english":"“ru”","romaji":"","kana":"る","tags":"hiragana, kana,lesson 10"},
{"english":"“re”","romaji":"","kana":"れ","tags":"hiragana, kana,lesson 10"},
{"english":"“ro”","romaji":"","kana":"ろ","tags":"hiragana, kana,lesson 10"},
{"english":"“wa”","romaji":"","kana":"わ","tags":"hiragana, kana,lesson "},
{"english":"“wo”","romaji":"","kana":"を","tags":"hiragana, kana,lesson "},
{"english":"“ga”","romaji":"","kana":"が","tags":"hiragana, kana,lesson "},
{"english":"“gi”","romaji":"","kana":"ぎ","tags":"hiragana, kana,lesson "},
{"english":"“gu”","romaji":"","kana":"ぐ","tags":"hiragana, kana,lesson "},
{"english":"“ge”","romaji":"","kana":"げ","tags":"hiragana, kana,lesson "},
{"english":"“go”","romaji":"","kana":"ご","tags":"hiragana, kana,lesson "},
{"english":"“za”","romaji":"","kana":"ざ","tags":"hiragana, kana,lesson "},
{"english":"“ji”","romaji":"","kana":"じ","tags":"hiragana, kana,lesson "},
{"english":"“zu”","romaji":"","kana":"ず","tags":"hiragana, kana,lesson "},
{"english":"“ze”","romaji":"","kana":"ぜ","tags":"hiragana, kana,lesson "},
{"english":"“zo”","romaji":"","kana":"ぞ","tags":"hiragana, kana,lesson "},
{"english":"“da”","romaji":"","kana":"だ","tags":"hiragana, kana,lesson "},
{"english":"“ji”","romaji":"","kana":"ぢ","tags":"hiragana, kana,lesson "},
{"english":"“zu”","romaji":"","kana":"づ","tags":"hiragana, kana,lesson "},
{"english":"“de”","romaji":"","kana":"で","tags":"hiragana, kana,lesson "},
{"english":"“do”","romaji":"","kana":"ど","tags":"hiragana, kana,lesson "},
{"english":"“ba”","romaji":"","kana":"ば","tags":"hiragana, kana,lesson "},
{"english":"“bi”","romaji":"","kana":"び","tags":"hiragana, kana,lesson "},
{"english":"“bu”","romaji":"","kana":"ぶ","tags":"hiragana, kana,lesson "},
{"english":"“be”","romaji":"","kana":"べ","tags":"hiragana, kana,lesson "},
{"english":"“bo”","romaji":"","kana":"ぼ","tags":"hiragana, kana,lesson "},
{"english":"“pa”","romaji":"","kana":"ぱ","tags":"hiragana, kana,lesson "},
{"english":"“pi”","romaji":"","kana":"ぴ","tags":"hiragana, kana,lesson "},
{"english":"“pu”","romaji":"","kana":"ぷ","tags":"hiragana, kana,lesson "},
{"english":"“pe”","romaji":"","kana":"ぺ","tags":"hiragana, kana,lesson "},
{"english":"“po”","romaji":"","kana":"ぽ","tags":"hiragana, kana,lesson "},
{"english":"\"kya\"","romaji":"","kana":"きゃ","tags":"hiragana, kana,lesson "},
{"english":"\"kyu\"","romaji":"","kana":"きゅ","tags":"hiragana, kana,lesson "},
{"english":"\"kyo\"","romaji":"","kana":"きょ","tags":"hiragana, kana,lesson "},
{"english":"\"sha\"","romaji":"","kana":"しゃ","tags":"hiragana, kana,lesson "},
{"english":"\"shu\"","romaji":"","kana":"しゅ","tags":"hiragana, kana,lesson "},
{"english":"\"sho\"","romaji":"","kana":"しょ","tags":"hiragana, kana,lesson "},
{"english":"\"cha\"","romaji":"","kana":"ちゃ","tags":"hiragana, kana,lesson "},
{"english":"\"chu\"","romaji":"","kana":"ちゅ","tags":"hiragana, kana,lesson "},
{"english":"\"cho\"","romaji":"","kana":"ちょ","tags":"hiragana, kana,lesson "},
{"english":"\"nya\"","romaji":"","kana":"にゃ","tags":"hiragana, kana,lesson "},
{"english":"\"nyu\"","romaji":"","kana":"にゅ","tags":"hiragana, kana,lesson "},
{"english":"\"nyo\"","romaji":"","kana":"にょ","tags":"hiragana, kana,lesson "},
{"english":"\"hya\"","romaji":"","kana":"ひゃ","tags":"hiragana, kana,lesson "},
{"english":"\"hyu\"","romaji":"","kana":"ひゅ","tags":"hiragana, kana,lesson "},
{"english":"\"hyo\"","romaji":"","kana":"ひょ","tags":"hiragana, kana,lesson "},
{"english":"\"mya\"","romaji":"","kana":"みゃ","tags":"hiragana, kana,lesson "},
{"english":"\"myu\"","romaji":"","kana":"みゅ","tags":"hiragana, kana,lesson "},
{"english":"\"myo\"","romaji":"","kana":"みょ","tags":"hiragana, kana,lesson "},
{"english":"\"rya\"","romaji":"","kana":"りゃ","tags":"hiragana, kana,lesson "},
{"english":"\"ryu\"","romaji":"","kana":"りゅ","tags":"hiragana, kana,lesson "},
{"english":"\"ryo\"","romaji":"","kana":"りょ","tags":"hiragana, kana,lesson "},
{"english":"\"gya\"","romaji":"","kana":"ぎゃ","tags":"hiragana, kana,lesson "},
{"english":"\"gyu\"","romaji":"","kana":"ぎゅ","tags":"hiragana, kana,lesson "},
{"english":"\"gyo\"","romaji":"","kana":"ぎょ","tags":"hiragana, kana,lesson "},
{"english":"\"jya\"","romaji":"","kana":"じゃ","tags":"hiragana, kana,lesson "},
{"english":"\"jyu\"","romaji":"","kana":"じゅ","tags":"hiragana, kana,lesson "},
{"english":"\"jyo\"","romaji":"","kana":"じょ","tags":"hiragana, kana,lesson "},
{"english":"\"dya\"","romaji":"","kana":"ぢゃ","tags":"hiragana, kana,lesson "},
{"english":"\"dyu\"","romaji":"","kana":"ぢゅ","tags":"hiragana, kana,lesson "},
{"english":"\"dyo\"","romaji":"","kana":"ぢょ","tags":"hiragana, kana,lesson "},
{"english":"\"bya\"","romaji":"","kana":"びゃ","tags":"hiragana, kana,lesson "},
{"english":"\"byu\"","romaji":"","kana":"びゅ","tags":"hiragana, kana,lesson "},
{"english":"\"byo\"","romaji":"","kana":"びょ","tags":"hiragana, kana,lesson "},
{"english":"\"pya\"","romaji":"","kana":"ぴゃ","tags":"hiragana, kana,lesson "},
{"english":"\"pyu\"","romaji":"","kana":"ぴゅ","tags":"hiragana, kana,lesson "},
{"english":"\"pyo\"","romaji":"","kana":"ぴょ","tags":"hiragana, kana,lesson "},
{"english":"awesome","romaji":"saikou","kana":"さいこう","tags":"conversation,lesson "},
{"english":"up","romaji":"jō","kana":"じょう","tags":"lesson "},
{"english":"down","romaji":"shita","kana":"した","tags":"lesson "},
{"english":"no problem","romaji":"zenzen daijoubu","kana":"ぜんぜんだいじょうぶ","tags":"conversation,lesson "},
{"english":"male, man","romaji":"otoko","kana":"おとこ","tags":"lesson "},
{"english":"boy","romaji":"otokonoko","kana":"おとこのこ","tags":"lesson "},
{"english":"fog, foggy","romaji":"kiri","kana":"きり","tags":"weather,lesson "},
{"english":"winter","romaji":"fuyu","kana":"ふゆ","tags":"lesson "},
{"english":"spring","romaji":"haru","kana":"はる","tags":"lesson "},
{"english":"summer","romaji":"natsu","kana":"なつ","tags":"lesson "},
{"english":"fall","romaji":"aki","kana":"あき","tags":"lesson "},
{"english":"work","romaji":"shigoto","kana":"しごと","tags":"lesson "},
{"english":"nose","romaji":"hana","kana":"はな","tags":"lesson "},
{"english":"chicken (animal)","romaji":"niwatori","kana":"にわとり","tags":"lesson "},
{"english":"egg","romaji":"tamago","kana":"たまご","tags":"lesson "},
{"english":"mouth","romaji":"kuchi","kana":"くち","tags":"lesson "},
{"english":"tooth","romaji":"ha","kana":"は","tags":"lesson "},
{"english":"how many?","romaji":"ikutsu","kana":"いくつ？","tags":"lesson "},
{"english":"(my) father","romaji":"chichi","kana":"ちち","tags":"lesson "},
{"english":"-years old","romaji":"-sai","kana":"〜さい","tags":"lesson "},
{"english":"(my) older sister","romaji":"ane","kana":"あね","tags":"lesson "},
{"english":"birthday","romaji":"tanjōbi","kana":"たんじょうび","tags":"lesson "},
{"english":"English","romaji":"Romaji","kana":"Kana","tags":"Tags,lesson Lesson"},
{"english":"\"a\"","romaji":"","kana":"ア","tags":"katakana, kana,lesson "},
{"english":"\"i\"","romaji":"","kana":"イ","tags":"katakana, kana,lesson "},
{"english":"\"u\"","romaji":"","kana":"ウ","tags":"katakana, kana,lesson "},
{"english":"\"e\"","romaji":"","kana":"エ","tags":"katakana, kana,lesson "},
{"english":"\"o\"","romaji":"","kana":"オ","tags":"katakana, kana,lesson "},
{"english":"\"ka\"","romaji":"","kana":"カ","tags":"katakana, kana,lesson "},
{"english":"\"ki\"","romaji":"","kana":"キ","tags":"katakana, kana,lesson "},
{"english":"\"ku\"","romaji":"","kana":"ク","tags":"katakana, kana,lesson "},
{"english":"\"ke\"","romaji":"","kana":"ケ","tags":"katakana, kana,lesson "},
{"english":"\"ko\"","romaji":"","kana":"コ","tags":"katakana, kana,lesson "},
{"english":"\"sa\"","romaji":"","kana":"サ","tags":"katakana, kana,lesson "},
{"english":"\"shi\"","romaji":"","kana":"シ","tags":"katakana, kana,lesson "},
{"english":"\"su\"","romaji":"","kana":"ス","tags":"katakana, kana,lesson "},
{"english":"\"se\"","romaji":"","kana":"セ","tags":"katakana, kana,lesson "},
{"english":"\"so\"","romaji":"","kana":"ソ","tags":"katakana, kana,lesson "},
{"english":"\"ta\"","romaji":"","kana":"タ","tags":"katakana, kana,lesson "},
{"english":"\"chi\"","romaji":"","kana":"チ","tags":"katakana, kana,lesson "},
{"english":"\"tsu\"","romaji":"","kana":"ツ","tags":"katakana, kana,lesson "},
{"english":"\"te\"","romaji":"","kana":"テ","tags":"katakana, kana,lesson "},
{"english":"\"to\"","romaji":"","kana":"ト","tags":"katakana, kana,lesson "},
{"english":"\"na\"","romaji":"","kana":"ナ","tags":"katakana, kana,lesson "},
{"english":"\"ni\"","romaji":"","kana":"ニ","tags":"katakana, kana,lesson "},
{"english":"\"nu\"","romaji":"","kana":"ヌ","tags":"katakana, kana,lesson "},
{"english":"\"ne\"","romaji":"","kana":"ネ","tags":"katakana, kana,lesson "},
{"english":"\"no\"","romaji":"","kana":"ノ","tags":"katakana, kana,lesson "},
{"english":"English","romaji":"Romaji","kana":"Kana","tags":"Tags,lesson Lesson"},
{"english":"this (thing)","romaji":"kore","kana":"これ","tags":"pronoun,lesson 7"},
{"english":"that (thing)","romaji":"sore","kana":"それ","tags":"pronoun,lesson 7"},
{"english":"that over there (thing)","romaji":"are","kana":"あれ","tags":"pronoun,lesson 7"},
{"english":"which (thing)","romaji":"dore","kana":"どれ","tags":"pronoun,lesson 7"},
{"english":"this (demonstrative)","romaji":"kono","kana":"この","tags":"pronoun,lesson 7"},
{"english":"that (demonstrative)","romaji":"sono","kana":"その","tags":"pronoun,lesson 7"},
{"english":"that over there (demonstrative)","romaji":"ano","kana":"あの","tags":"pronoun,lesson 7"},
{"english":"which (demonstrative)","romaji":"dono","kana":"どの","tags":"pronoun,lesson 7"},
{"english":"made in Japan","romaji":"Nihon no","kana":"にほんの","tags":"lesson 7"},
{"english":"one (counting, general)","romaji":"hitotsu","kana":"ひとつ","tags":"counting,lesson 7"},
{"english":"two (counting, general)","romaji":"futatsu","kana":"ふたつ","tags":"counting,lesson 7"},
{"english":"three (counting, general)","romaji":"mittsu","kana":"みっつ","tags":"counting,lesson 7"},
{"english":"four (counting, general)","romaji":"yottsu","kana":"よっつ","tags":"counting,lesson 7"},
{"english":"five (counting, general)","romaji":"itsutsu","kana":"いつつ","tags":"counting,lesson 7"},
{"english":"six (counting, general)","romaji":"muttsu","kana":"むっつ","tags":"counting,lesson 7"},
{"english":"seven (counting, general)","romaji":"nanatsu","kana":"ななつ","tags":"counting,lesson 7"},
{"english":"eight (counting, general)","romaji":"yattsu","kana":"やっつ","tags":"counting,lesson 7"},
{"english":"nine (counting, general)","romaji":"kokonotsu","kana":"ここのこつ","tags":"counting,lesson 7"},
{"english":"ten (counting, general)","romaji":"jikko","kana":"じっこ","tags":"counting,lesson 7"},
{"english":"one (counting, long & slender)","romaji":"ippon","kana":"いっぽん","tags":"counting,lesson 7"},
{"english":"two (counting, long & slender)","romaji":"ni-hon","kana":"にほん","tags":"counting,lesson 7"},
{"english":"three (counting, long & slender)","romaji":"san-bon","kana":"さんぼん","tags":"counting,lesson 7"},
{"english":"four (counting, long & slender)","romaji":"yon-hon","kana":"よんほん","tags":"counting,lesson 7"},
{"english":"five (counting, long & slender)","romaji":"go-hon","kana":"ごほん","tags":"counting,lesson 7"},
{"english":"six (counting, long & slender)","romaji":"roppon","kana":"ろっぽん","tags":"counting,lesson 7"},
{"english":"seven (counting, long & slender)","romaji":"nana-hon","kana":"ななほん","tags":"counting,lesson 7"},
{"english":"eight (counting, long & slender)","romaji":"happon","kana":"はっぽん","tags":"counting,lesson 7"},
{"english":"nine (counting, long & slender)","romaji":"kyū-hon","kana":"きゅうほん","tags":"counting,lesson 7"},
{"english":"ten (counting, long & slender)","romaji":"juppon","kana":"じゅうぽん","tags":"counting,lesson 7"},
{"english":"1,000","romaji":"sen","kana":"せん","tags":"numbers,lesson 7"},
{"english":"2,000","romaji":"nisen","kana":"にせん","tags":"numbers,lesson 7"},
{"english":"3,000","romaji":"sanzen","kana":"さんぜん","tags":"numbers,lesson 7"},
{"english":"4,000","romaji":"yonsen","kana":"よんせん","tags":"numbers,lesson 7"},
{"english":"5,000","romaji":"gosen","kana":"ごせん","tags":"numbers,lesson 7"},
{"english":"6,000","romaji":"rokusen","kana":"ろくせん","tags":"numbers,lesson 7"},
{"english":"7,000","romaji":"nanasen","kana":"ななせん","tags":"numbers,lesson 7"},
{"english":"8,000","romaji":"hassen","kana":"はっせん","tags":"numbers,lesson 7"},
{"english":"9,000","romaji":"kyūsen","kana":"きゅうせん","tags":"numbers,lesson 7"},
{"english":"10,000","romaji":"ichi-man","kana":"いちまん","tags":"numbers,lesson 7"},
{"english":"100,000","romaji":"jū-man","kana":"じゅうまん","tags":"numbers,lesson 7"},
{"english":"shirt","romaji":"shatsu","kana":"シャツ","tags":"clothing,lesson 7"},
{"english":"sweater","romaji":"sētā","kana":"セーター","tags":"clothing,lesson 7"},
{"english":"bread","romaji":"pan","kana":"パン","tags":"food,lesson 7"},
{"english":"pizza","romaji":"piza","kana":"ピザ","tags":"food,lesson 7"},
{"english":"ice cream","romaji":"aisu(kuriimu)","kana":"アイス（クリーム）","tags":"food,lesson 7"},
{"english":"wine","romaji":"wain","kana":"ワイン","tags":"food,lesson 7"},
{"english":"Germany","romaji":"Doritsu","kana":"ドイツ","tags":"countries,lesson 7"},
{"english":"Italy","romaji":"Itaria","kana":"イタリア","tags":"countries,lesson 7"},
{"english":"France","romaji":"Furansu","kana":"フランス","tags":"countries,lesson 7"},
{"english":"Switzerland","romaji":"Suisu","kana":"スイス","tags":"countries,lesson 7"},
{"english":"of which country","romaji":"doko no","kana":"どこの","tags":"countries,lesson 7"},
{"english":"counter (thin & flat)","romaji":"-mai","kana":"〜まい","tags":"counting,lesson 7"},
{"english":"how many","romaji":"ikutsu","kana":"いくつ","tags":"counting,lesson 7"},
{"english":"and","romaji":"sorekara","kana":"それから","tags":"lesson 7"},
{"english":"photograph","romaji":"shashin","kana":"しゃしん","tags":"lesson 7"},
{"english":"woman","romaji":"onna no hito","kana":"おんなの　ひと","tags":"people,lesson 7"},
{"english":"woman, female","romaji":"onna","kana":"おんな","tags":"people,lesson 7"},
{"english":"who (polite)","romaji":"donata","kana":"どなた","tags":"people,lesson 7"},
{"english":"boy","romaji":"otoko no ko","kana":"おとこの　こ","tags":"people,lesson 7"},
{"english":"man, male","romaji":"otoko","kana":"おとこ","tags":"people,lesson 7"},
{"english":"child","romaji":"ko","kana":"こ","tags":"people,lesson 7"},
{"english":"which","romaji":"dono","kana":"どの","tags":"lesson 7"},
{"english":"(said before eating)","romaji":"itadakimasu","kana":"いただきます","tags":"phrases,lesson "},
{"english":"(said after eating)","romaji":"gachisōsama-deshita","kana":"ごちそうさまでした","tags":"phrases,lesson "},
{"english":"strong","romaji":"chikara","kana":"ちから","tags":"lesson "},
{"english":"sword","romaji":"katana","kana":"刀","tags":"lesson "},
{"english":"red","romaji":"aka","kana":"あか","tags":"colors,lesson 8"},
{"english":"baby","romaji":"akachan","kana":"あかちゃん","tags":"people,lesson "},
{"english":"family","romaji":"kazoku","kana":"かそく","tags":"people, family,lesson "},
{"english":"blue","romaji":"ao","kana":"あお","tags":"colors,lesson 8"},
{"english":"no way! (very casual)","romaji":"uso","kana":"ウソ","tags":"phrases,lesson "},
{"english":"sunny","romaji":"hare","kana":"はれ","tags":"weather,lesson "},
{"english":"are you eating here?","romaji":"koko de omeshiagari desu ka","kana":"ここでおめしあがりですか","tags":"phrases,lesson "},
{"english":"(fried) potato","romaji":"poteto","kana":"ポテト","tags":"food,lesson 8"},
{"english":"coke","romaji":"kōra","kana":"コーラ","tags":"food,lesson 8"},
{"english":"large, big","romaji":"ōkii","kana":"おおきい","tags":"lesson 8"},
{"english":"small","romaji":"chiisai","kana":"ちいさい","tags":"lesson 8"},
{"english":"hamburger","romaji":"hambāgā","kana":"ハンバーガー","tags":"food,lesson 8"},
{"english":"salad","romaji":"sarada","kana":"サラダ","tags":"food,lesson 8"},
{"english":"juice (sweet drink)","romaji":"jūsu","kana":"ジュース","tags":"food,lesson 8"},
{"english":"milk","romaji":"miruku","kana":"ミルク","tags":"food,lesson 8"},
{"english":"coffee","romaji":"kōhii","kana":"コーヒー","tags":"food,lesson 8"},
{"english":"expensive","romaji":"takai","kana":"たかい","tags":"money,lesson 8"},
{"english":"cheap","romaji":"yasui","kana":"やすい","tags":"monet,lesson 8"},
{"english":"white (i-adj.)","romaji":"shiroi","kana":"うぃどい","tags":"colors,lesson 8"},
{"english":"black (i-adj.)","romaji":"kuroi","kana":"くろい","tags":"colors,lesson 8"},
{"english":"all white","romaji":"mashiro","kana":"ましろ","tags":"colors,lesson "},
{"english":"all black","romaji":"makuro","kana":"まくろ","tags":"colors,lesson "},
{"english":"all red","romaji":"maka","kana":"まっあか","tags":"colors,lesson "},
{"english":"pale","romaji":"masuo","kana":"まっさお","tags":"colors,lesson "},
{"english":"a moment (formal)","romaji":"shōshō","kana":"しょうしょう","tags":"phrases,lesson 8"},
{"english":"please wait (polite)","romaji":"o-machi kudasai","kana":"おまちください","tags":"phrases,lesson 8"},
{"english":"wait","romaji":"machimasu (matsu)","kana":"まちます　（まつ）","tags":"phrases,lesson 8"},
{"english":"to-go (food)","romaji":"omochikaeri","kana":"おまちかえり","tags":"restaurant,lesson 8"},
{"english":"menu","romaji":"menyū","kana":"メニュー","tags":"restaurant,lesson 8"},
{"english":"what kind of","romaji":"nan no","kana":"なんの","tags":"phrases,lesson 8"},
{"english":"print-out","romaji":"purinto","kana":"プリント","tags":"lesson 8"},
{"english":"more","romaji":"mō","kana":"もう","tags":"lesson 8"},
{"english":"ah","romaji":"a","kana":"あ","tags":"phrases,lesson 8"}];
